import type { SafetySession, IncidentReport } from '../types';

export const INITIAL_SESSIONS: SafetySession[] = [
  // --- NIGERIA (Lagos & Abuja) ---
  {
    id: 'sess-101',
    userId: 'usr-001',
    userName: 'Amina Bello',
    userPhone: '+234 803 123 4567',
    userEmail: 'amina.bello@example.com',
    status: 'emergency',
    batteryLevel: 24,
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'yaba-lagos-mainland',
    lastPingAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    emergencyTriggeredAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    currentLocation: { lat: 6.5180, lng: 3.3780 }, // Lagos Central / Yaba
    addressName: 'Herbert Macaulay Way, Yaba, Lagos',
    breadcrumbs: [
      { lat: 6.5120, lng: 3.3750, recordedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString() },
      { lat: 6.5150, lng: 3.3770, recordedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
      { lat: 6.5170, lng: 3.3778, recordedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString() },
      { lat: 6.5180, lng: 3.3780, recordedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-101',
  },
  {
    id: 'sess-102',
    userId: 'usr-002',
    userName: 'Chidi Okafor',
    userPhone: '+234 812 987 6543',
    userEmail: 'chidi.okafor@example.com',
    status: 'distress_pending',
    batteryLevel: 68,
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'ikeja-capital-sector',
    lastPingAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    currentLocation: { lat: 6.6018, lng: 3.3515 }, // Ikeja
    addressName: 'Allen Avenue, Ikeja, Lagos',
    breadcrumbs: [
      { lat: 6.5910, lng: 3.3390, recordedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
      { lat: 6.6018, lng: 3.3515, recordedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-102',
  },
  {
    id: 'sess-103',
    userId: 'usr-003',
    userName: 'David Adeleke',
    userPhone: '+234 701 555 0192',
    userEmail: 'david.adeleke@example.com',
    status: 'active',
    batteryLevel: 89,
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'victoria-island-oniru',
    lastPingAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    currentLocation: { lat: 6.4281, lng: 3.4219 }, // Victoria Island
    addressName: 'Ahmadu Bello Way, Victoria Island',
    breadcrumbs: [
      { lat: 6.4250, lng: 3.4190, recordedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
      { lat: 6.4281, lng: 3.4219, recordedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-103',
  },
  {
    id: 'sess-104',
    userId: 'usr-004',
    userName: 'Fatima Al-Hassan',
    userPhone: '+234 809 444 8821',
    userEmail: 'fatima.alhassan@example.com',
    status: 'active',
    batteryLevel: 94,
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'lekki-phase-1-ikate',
    lastPingAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 4 * 60 * 1000).toISOString(),
    currentLocation: { lat: 6.4698, lng: 3.4752 }, // Lekki Phase 1
    addressName: 'Admiralty Way, Lekki Phase 1',
    breadcrumbs: [
      { lat: 6.4670, lng: 3.4710, recordedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString() },
      { lat: 6.4698, lng: 3.4752, recordedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-104',
  },
  {
    id: 'sess-105',
    userId: 'usr-005',
    userName: 'Zainab Mohammed',
    userPhone: '+234 802 333 9911',
    userEmail: 'zainab.m@example.com',
    status: 'active',
    batteryLevel: 76,
    countryCode: 'NG',
    stateCode: 'FC',
    communityId: 'maitama-diplomatic-sector',
    lastPingAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 2 * 60 * 1000).toISOString(),
    currentLocation: { lat: 9.0880, lng: 7.4980 }, // Maitama, Abuja
    addressName: 'Aguiyi Ironsi St, Maitama, Abuja',
    breadcrumbs: [
      { lat: 9.0850, lng: 7.4940, recordedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString() },
      { lat: 9.0880, lng: 7.4980, recordedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-105',
  },

  // --- UNITED KINGDOM (London) ---
  {
    id: 'sess-201',
    userId: 'usr-006',
    userName: 'Oliver Taylor',
    userPhone: '+44 7700 900123',
    userEmail: 'oliver.taylor@example.co.uk',
    status: 'distress_pending',
    batteryLevel: 41,
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'city-of-westminster-victoria-soho',
    lastPingAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    currentLocation: { lat: 51.4975, lng: -0.1357 },
    addressName: 'Victoria Street, Westminster, London',
    breadcrumbs: [
      { lat: 51.5010, lng: -0.1410, recordedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString() },
      { lat: 51.4975, lng: -0.1357, recordedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-201',
  },
  {
    id: 'sess-202',
    userId: 'usr-007',
    userName: 'Emma Watson-Smith',
    userPhone: '+44 7700 900567',
    userEmail: 'emma.ws@example.co.uk',
    status: 'active',
    batteryLevel: 82,
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'canary-wharf-isle-of-dogs',
    lastPingAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    currentLocation: { lat: 51.5054, lng: -0.0235 },
    addressName: 'Bank Street, Canary Wharf, London',
    breadcrumbs: [
      { lat: 51.5030, lng: -0.0210, recordedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
      { lat: 51.5054, lng: -0.0235, recordedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-202',
  },

  // --- UNITED STATES (New York & California) ---
  {
    id: 'sess-301',
    userId: 'usr-008',
    userName: 'Marcus Sterling',
    userPhone: '+1 212 555 0184',
    userEmail: 'marcus.sterling@example.com',
    status: 'emergency',
    batteryLevel: 19,
    countryCode: 'US',
    stateCode: 'NY',
    communityId: 'manhattan-times-square-midtown',
    lastPingAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    emergencyTriggeredAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    currentLocation: { lat: 40.7580, lng: -73.9855 },
    addressName: 'Broadway & 45th St, Times Square, Manhattan, NY',
    breadcrumbs: [
      { lat: 40.7520, lng: -73.9870, recordedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
      { lat: 40.7580, lng: -73.9855, recordedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-301',
  },
  {
    id: 'sess-302',
    userId: 'usr-009',
    userName: 'Sarah Jenkins',
    userPhone: '+1 415 555 0133',
    userEmail: 'sarah.j@example.com',
    status: 'active',
    batteryLevel: 91,
    countryCode: 'US',
    stateCode: 'CA',
    communityId: 'san-francisco-financial-district-soma',
    lastPingAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 4 * 60 * 1000).toISOString(),
    currentLocation: { lat: 37.7880, lng: -122.4000 },
    addressName: 'Market St & 3rd St, SoMa, San Francisco, CA',
    breadcrumbs: [
      { lat: 37.7850, lng: -122.4030, recordedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString() },
      { lat: 37.7880, lng: -122.4000, recordedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-302',
  },

  // --- KENYA (Nairobi) ---
  {
    id: 'sess-401',
    userId: 'usr-010',
    userName: 'Kelvin Kipchoge',
    userPhone: '+254 712 345 678',
    userEmail: 'kelvin.k@example.co.ke',
    status: 'active',
    batteryLevel: 63,
    countryCode: 'KE',
    stateCode: '30',
    communityId: 'westlands-parklands-sarit-mpaka',
    lastPingAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 1 * 60 * 1000).toISOString(),
    currentLocation: { lat: -1.2650, lng: 36.8050 },
    addressName: 'Mpaka Road, Westlands, Nairobi',
    breadcrumbs: [
      { lat: -1.2620, lng: 36.8010, recordedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
      { lat: -1.2650, lng: 36.8050, recordedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-401',
  },
];

export const INITIAL_REPORTS: IncidentReport[] = [
  // Nigeria (Lagos & Abuja)
  {
    id: 'rep-201',
    isAnonymous: false,
    reportedBy: 'usr-001',
    reporterName: 'Amina Bello',
    source: 'safety_mode_emergency',
    category: 'emergency',
    urgency: 'critical',
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'yaba-lagos-mainland',
    title: 'Missed Safety Check-in (Emergency Mode Triggered)',
    description: 'User initiated Safety Mode at 21:15. Two consecutive heartbeat check-ins timed out without response. Auto-escalation dispatched.',
    location: { lat: 6.5180, lng: 3.3780 },
    addressName: 'Herbert Macaulay Way, Yaba, Lagos',
    status: 'investigating',
    staffComments: [
      {
        id: 'comm-1',
        staffName: 'Officer K. Mensah',
        staffRole: 'Dispatch Supervisor',
        comment: 'Attempted phone call at 21:26 (no answer). Connecting in-app voice call to check in.',
        createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      },
      {
        id: 'comm-2',
        staffName: 'Officer K. Mensah',
        staffRole: 'Dispatch Supervisor',
        comment: 'Responder unit routed to location. ETA 4 mins.',
        createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-202',
    isAnonymous: true,
    source: 'community_report',
    category: 'harassment',
    urgency: 'high',
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'yaba-lagos-mainland',
    title: 'Aggressive group harassing pedestrians near underpass',
    description: 'Group of three young men blocking pedestrian walkway demanding money near the bus stop. Streetlights are currently out.',
    location: { lat: 6.5195, lng: 3.3710 },
    addressName: 'Tejuosho Underpass, Yaba',
    status: 'open',
    staffComments: [
      {
        id: 'comm-3',
        staffName: 'T. Johnson',
        staffRole: 'Community Moderator',
        comment: 'Cross-referenced with local community security post. Increased patrol requested.',
        createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-203',
    isAnonymous: false,
    reportedBy: 'usr-005',
    reporterName: 'Emeka Nwosu',
    source: 'community_report',
    category: 'theft',
    urgency: 'medium',
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'ikeja-capital-sector',
    title: 'Phone snatching incident reported from motorbike',
    description: 'Unregistered black motorcycle snatched a commuter handbag and sped off towards the expressway.',
    location: { lat: 6.5920, lng: 3.3440 },
    addressName: 'Toyin Street Junction, Ikeja',
    status: 'investigating',
    staffComments: [],
    createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    id: 'rep-204',
    isAnonymous: true,
    source: 'community_report',
    category: 'hazard',
    urgency: 'low',
    countryCode: 'NG',
    stateCode: 'LA',
    communityId: 'lekki-phase-1-ikate',
    title: 'Open manhole on dark sidewalk',
    description: 'Uncovered storm drain without warning barricades right in front of the convenience store.',
    location: { lat: 6.4710, lng: 3.4750 },
    addressName: 'Admiralty Way, Lekki',
    status: 'resolved',
    staffComments: [
      {
        id: 'comm-4',
        staffName: 'S. Adele',
        staffRole: 'Municipal Liaison',
        comment: 'Temporary safety cone placed. Public Works notified for concrete replacement.',
        createdAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 180 * 60 * 1000).toISOString(),
  },

  // United Kingdom (London)
  {
    id: 'rep-301',
    isAnonymous: false,
    reportedBy: 'usr-006',
    reporterName: 'Oliver Taylor',
    source: 'community_report',
    category: 'theft',
    urgency: 'medium',
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'city-of-westminster-victoria-soho',
    title: 'Bicycle lock severed near tube station',
    description: 'Electric bike stolen outside St James Park Station entrance between 18:00 and 19:30.',
    location: { lat: 51.4990, lng: -0.1340 },
    addressName: 'Broadway, Westminster, London',
    status: 'open',
    staffComments: [],
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },

  // United States (New York)
  {
    id: 'rep-401',
    isAnonymous: false,
    reportedBy: 'usr-008',
    reporterName: 'Marcus Sterling',
    source: 'safety_mode_emergency',
    category: 'emergency',
    urgency: 'critical',
    countryCode: 'US',
    stateCode: 'NY',
    communityId: 'manhattan-times-square-midtown',
    title: 'SOS Broadcast Alert - Night Transit Corridor',
    description: 'Panic beacon activated via device volume button long-press. GPS location locked.',
    location: { lat: 40.7580, lng: -73.9855 },
    addressName: '7th Ave & W 46th St, Manhattan, NY',
    status: 'investigating',
    staffComments: [
      {
        id: 'comm-5',
        staffName: 'Dispatch NYC-2',
        staffRole: 'NYPD / Community Safety Liaison',
        comment: 'Responder team dispatched to Times Square location.',
        createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },

  // Kenya (Nairobi)
  {
    id: 'rep-501',
    isAnonymous: true,
    source: 'community_report',
    category: 'hazard',
    urgency: 'medium',
    countryCode: 'KE',
    stateCode: '30',
    communityId: 'westlands-parklands-sarit-mpaka',
    title: 'Downed power line across walkway following heavy rain',
    description: 'Sparking electrical cable dangling near pedestrian footbridge over Ring Road.',
    location: { lat: -1.2670, lng: 36.8080 },
    addressName: 'Ring Road Westlands, Nairobi',
    status: 'investigating',
    staffComments: [
      {
        id: 'comm-6',
        staffName: 'Officer J. Ochieng',
        staffRole: 'Emergency Dispatch',
        comment: 'Kenya Power emergency maintenance crew dispatched.',
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

import type { StaffMember } from '../types';

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'stf-001',
    name: 'Sarah Jenkins',
    email: 'admin@safety.org',
    phone: '+234 803 111 2233',
    role: 'super_admin',
    status: 'on_duty',
    countryCode: 'ALL',
    assignedJurisdiction: 'Global',
    lastActiveAt: new Date().toISOString(),
    createdAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'stf-002',
    name: 'Officer Babatunde Adeyemi',
    email: 'babatunde.a@safety.org',
    phone: '+234 812 444 5566',
    role: 'dispatch_officer',
    status: 'on_duty',
    countryCode: 'NG',
    assignedJurisdiction: 'Nigeria',
    lastActiveAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'stf-003',
    name: 'Inspector James Ochieng',
    email: 'j.ochieng@safety.org',
    phone: '+254 711 999 888',
    role: 'dispatch_officer',
    status: 'on_duty',
    countryCode: 'KE',
    assignedJurisdiction: 'Kenya',
    lastActiveAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'stf-004',
    name: 'Sergeant Marcus Holloway',
    email: 'm.holloway@safety.org',
    phone: '+44 7700 900123',
    role: 'field_responder',
    status: 'active',
    countryCode: 'GB',
    assignedJurisdiction: 'United Kingdom',
    lastActiveAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'stf-005',
    name: 'Elena Rostova',
    email: 'e.rostova@safety.org',
    phone: '+1 212 555 0199',
    role: 'support_lead',
    status: 'active',
    countryCode: 'US',
    assignedJurisdiction: 'United States',
    lastActiveAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'stf-006',
    name: 'Dr. Chidi Okafor',
    email: 'c.okafor@safety.org',
    phone: '+234 809 777 3322',
    role: 'field_responder',
    status: 'offline',
    countryCode: 'NG',
    assignedJurisdiction: 'Nigeria',
    lastActiveAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

