import type { SafetySession, IncidentReport } from '../types';

export const INITIAL_SESSIONS: SafetySession[] = [
  // --- UNITED KINGDOM (London) ---
  {
    id: 'sess-201',
    userId: 'usr-006',
    userName: 'Oliver Taylor',
    userPhone: '+44 7700 900123',
    userEmail: 'oliver.taylor@example.co.uk',
    status: 'distress_pending',
    batteryLevel: 41,
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'city-of-westminster-victoria-soho',
    lastPingAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    currentLocation: { lat: 51.4975, lng: -0.1357 },
    addressName: 'Victoria Street, Westminster, London',
    breadcrumbs: [
      { lat: 51.5010, lng: -0.1410, recordedAt: new Date(Date.now() - 18 * 60 * 1000).toISOString() },
      { lat: 51.4975, lng: -0.1357, recordedAt: new Date(Date.now() - 7 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-201',
  },
  {
    id: 'sess-202',
    userId: 'usr-007',
    userName: 'Emma Watson-Smith',
    userPhone: '+44 7700 900567',
    userEmail: 'emma.ws@example.co.uk',
    status: 'active',
    batteryLevel: 82,
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'canary-wharf-isle-of-dogs',
    lastPingAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    currentLocation: { lat: 51.5054, lng: -0.0235 },
    addressName: 'Bank Street, Canary Wharf, London',
    breadcrumbs: [
      { lat: 51.5030, lng: -0.0210, recordedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString() },
      { lat: 51.5054, lng: -0.0235, recordedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-202',
  },

  // --- UNITED STATES (New York & California) ---
  {
    id: 'sess-301',
    userId: 'usr-008',
    userName: 'Marcus Sterling',
    userPhone: '+1 212 555 0184',
    userEmail: 'marcus.sterling@example.com',
    status: 'emergency',
    batteryLevel: 19,
    countryCode: 'US',
    stateCode: 'NY',
    communityId: 'manhattan-times-square-midtown',
    lastPingAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    emergencyTriggeredAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    currentLocation: { lat: 40.7580, lng: -73.9855 },
    addressName: 'Broadway & 45th St, Times Square, Manhattan, NY',
    breadcrumbs: [
      { lat: 40.7520, lng: -73.9870, recordedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString() },
      { lat: 40.7580, lng: -73.9855, recordedAt: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-301',
  },
  {
    id: 'sess-302',
    userId: 'usr-009',
    userName: 'Sarah Jenkins',
    userPhone: '+1 415 555 0133',
    userEmail: 'sarah.j@example.com',
    status: 'active',
    batteryLevel: 91,
    countryCode: 'US',
    stateCode: 'CA',
    communityId: 'san-francisco-financial-district-soma',
    lastPingAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 4 * 60 * 1000).toISOString(),
    currentLocation: { lat: 37.7880, lng: -122.4000 },
    addressName: 'Market St & 3rd St, SoMa, San Francisco, CA',
    breadcrumbs: [
      { lat: 37.7850, lng: -122.4030, recordedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString() },
      { lat: 37.7880, lng: -122.4000, recordedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-302',
  },

  // --- KENYA (Nairobi) ---
  {
    id: 'sess-401',
    userId: 'usr-010',
    userName: 'Kelvin Kipchoge',
    userPhone: '+254 712 345 678',
    userEmail: 'kelvin.k@example.co.ke',
    status: 'active',
    batteryLevel: 63,
    countryCode: 'KE',
    stateCode: '30',
    communityId: 'westlands-parklands-sarit-mpaka',
    lastPingAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    nextPromptDueAt: new Date(Date.now() + 1 * 60 * 1000).toISOString(),
    currentLocation: { lat: -1.2650, lng: 36.8050 },
    addressName: 'Mpaka Road, Westlands, Nairobi',
    breadcrumbs: [
      { lat: -1.2620, lng: 36.8010, recordedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
      { lat: -1.2650, lng: 36.8050, recordedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
    ],
    agoraChannelName: 'session-sess-401',
  },
];

export const INITIAL_REPORTS: IncidentReport[] = [
  // United Kingdom (London)
  {
    id: 'rep-301',
    isAnonymous: false,
    reportedBy: 'usr-006',
    reporterName: 'Oliver Taylor',
    source: 'community_report',
    category: 'theft',
    urgency: 'medium',
    countryCode: 'GB',
    stateCode: 'LND',
    communityId: 'city-of-westminster-victoria-soho',
    title: 'Bicycle lock severed near tube station',
    description: 'Electric bike stolen outside St James Park Station entrance between 18:00 and 19:30.',
    location: { lat: 51.4990, lng: -0.1340 },
    addressName: 'Broadway, Westminster, London',
    status: 'open',
    staffComments: [],
    createdAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
  },

  // United States (New York)
  {
    id: 'rep-401',
    isAnonymous: false,
    reportedBy: 'usr-008',
    reporterName: 'Marcus Sterling',
    source: 'safety_mode_emergency',
    category: 'emergency',
    urgency: 'critical',
    countryCode: 'US',
    stateCode: 'NY',
    communityId: 'manhattan-times-square-midtown',
    title: 'SOS Broadcast Alert - Night Transit Corridor',
    description: 'Panic beacon activated via device volume button long-press. GPS location locked.',
    location: { lat: 40.7580, lng: -73.9855 },
    addressName: '7th Ave & W 46th St, Manhattan, NY',
    status: 'investigating',
    staffComments: [
      {
        id: 'comm-5',
        staffName: 'Dispatch NYC-2',
        staffRole: 'NYPD / Community Safety Liaison',
        comment: 'Responder team dispatched to Times Square location.',
        createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },

  // Kenya (Nairobi)
  {
    id: 'rep-501',
    isAnonymous: true,
    source: 'community_report',
    category: 'hazard',
    urgency: 'medium',
    countryCode: 'KE',
    stateCode: '30',
    communityId: 'westlands-parklands-sarit-mpaka',
    title: 'Downed power line across walkway following heavy rain',
    description: 'Sparking electrical cable dangling near pedestrian footbridge over Ring Road.',
    location: { lat: -1.2670, lng: 36.8080 },
    addressName: 'Ring Road Westlands, Nairobi',
    status: 'investigating',
    staffComments: [
      {
        id: 'comm-6',
        staffName: 'Officer J. Ochieng',
        staffRole: 'Emergency Dispatch',
        comment: 'Kenya Power emergency maintenance crew dispatched.',
        createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      },
    ],
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
];

import type { StaffMember } from '../types';

export const INITIAL_STAFF: StaffMember[] = [];

